---
title: "glm_modelling_jd"
author: "MostMisidentifiedSpecies Team"
date: '2020-06-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import data}
library(tidyverse)

data<-read.csv("../data/iNatDataset_Normalized_SpeciesCount_SubsetforAnalysis.csv")

```

```{r clean data}
##removing row count column
data<-data[c(-1)]

##removing casual grade observations
data <- data[! data$quality_grade == "casual",]

##removing NAs/RatioMisID>0
finaldata <- data %>% subset(RatioDisagree>0)

##removing observations not ID to species level
finaldata <- finaldata[finaldata$taxon.rank == "species",]
  
```

```{r selecting parameters to explore}

##hypotheses

```

```{r correlation matrix on parameters of interest}
##corrmatrix
library(Hmisc)
library(corrplot)

s_corrmatrix <- cor(finaldata[, colnames(finaldata) %in% c("species_count","user.identifications_count", "taxon.observations_count", "taxon.taxon_changes_count", "comments_count")], method = "spearman")

round(s_corrmatrix, 3)
corrplot(s_corrmatrix)

s_corr <- rcorr(as.matrix(s_corrmatrix, type = c("spearman")))
s_corr$r
s_corr$P

p_corrmatrix <- cor(finaldata[, colnames(finaldata) %in% c("species_count","user.identifications_count", "taxon.observations_count", "taxon.taxon_changes_count", "comments_count")], method = "pearson")

round(p_corrmatrix, 3)
corrplot(p_corrmatrix)

p_corr <- rcorr(as.matrix(p_corrmatrix, type = c("pearson")))
p_corr$r
p_corr$P

##deciding which correlated parameters to use

```

```{r building glm models}

##building glm w/ hypothesized, uncorrelated parameters

##looking at results

```

```{r creating glm result figure}

##creating forest plot - or similar

```