---
title: "Get data"
author: "MostMisidentifiedSpecies team"
date: '2020-05-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Import data for observed bees in Canada as of 2020-05-27, 3:30pm


### Import data using the API

```{r import data directly from API}

# Libraries
library("tidyverse")
library("httr")
library("jsonlite")

# Set API url
api <- "https://api.inaturalist.org/v1/observations"

# Define query
fetch <- list("per_page" = 200,
              "order" = "desc", 
              "order_by" = "created_at",
              "place_id" = 6712,                    # Quebec(13336) Montreal(139965) Laval (27655) Canada (6712)
              "taxon_id" = 47221)                   # Honey Bees, Bumble Bees, and Allies (47221)

# Get first result from API
res <- GET(api, query=c(fetch, list(page=1)))    
resDF <- fromJSON(httr::content(res, as = "text"),flatten=TRUE)

# How many observations? Too many... 259899
resDF$total_results

# Since number observations > 10000, go by sections of 10 degrees of longitude 
swlng <- c(-141,-130,-120,-110,-100,-90,-80,-70,-60)
nelng <-  c(-130,-120,-110,-100,-90,-80,-70,-60,-52)

  # # Loop through 10 degrees of longitude sections
  for(j in 1:length(swlng)){
    # # # Define query
    fetch <- list("per_page" = 200,
                "order" = "desc", 
                "order_by" = "created_at",
                "swlng" = swlng[j],                   # Limit query to ~10 degrees of longitude
                "nelng" = nelng[j],
                "place_id" = 6712,                    # Quebec(13336) Montreal(139965) Laval (27655) Canada (6712)
                "taxon_id" = 47221)                   # Honey Bees, Bumble Bees, and Allies (47221)
    
    # # # Get first result from API
    res <- GET(api, query=c(fetch, list(page=1)))    
    resDF <- fromJSON(httr::content(res, as = "text"),flatten=TRUE)
    
    # # # Limit number of resuts to 10000
    if (resDF$total_results < 10001 & resDF$total_results > 200) {
    
      # # # # Get all results from API
      for (i in 2:(ceiling(resDF$total_results/resDF$per_page))) {
            res.t <- GET(api, query=c(fetch,list(page=i)))
            resDF.t <- fromJSON(httr::content(res.t, as = "text"),flatten=TRUE)
            resDF$results <- bind_rows(resDF$results,resDF.t$results)
            Sys.sleep(1)
      }
      
      # # # # Store observations per page    
      data_loop <- resDF$results
    }
    
    # # # Store observations per sections of 10 degrees of longitude
    if(j == 1){
      data_api <- data_loop
    }else{
      data_api <- bind_rows(data_api,data_loop)
    }
  }

# View                    
View(data_api[1:5,])

```


The dataset *data_api* is comprized of 25899 records and 154 columns/variables.


## Save data

The dataset is too large to be uploaded into github at once. It will be breaken into smaller subfiles.

```{r Save data}

# Number of subfiles desired
noSubFiles <- 3

  # # Verify the number of subfiles will contain an equal amount of observations (can't have 1233.4 observations per file!)
  length(data_api$uuid)/3 == ceiling(length(data_api$uuid)/3)

# Save data
for(i in 1:noSubFiles){
  firstObs <- 1+(i-1)*length(data_api$uuid)/3
  lastObs <- i*length(data_api$uuid)/3
  saveRDS(data_api[firstObs:lastObs,], file = paste(i,"-Can_bees_API_2020-05-27.rds",sep = ""))
}

```

