---
title: "Taxon rank figure creation"
author: "MostMisidentifiedSpecies team"
date: "2020-06-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import data using iNatTools package}

# Libraries
library("tidyverse")

# Import data subfiles and reassemble the dataset
for(i in 1:3){
  subFile <- readRDS(paste("../data/",i,"-Can_bees_API_2020-05-27.rds",sep = ""))
  
  if(i == 1) data_api <- subFile
  if(i > 1) data_api <- bind_rows(data_api,subFile)
}

```

The dataset *data* is comprized of 25899 records and 154 columns/variables.


## Lets remove these casual quality grade observations from data_api to avoid mistakes

```{r clean data}

# Remove casual quality grade observations
data <- data_api[! data_api$quality_grade == "casual",]

```




```{r Disagreement ratio}

data$RatioMisId<- data$num_identification_disagreements/data$identifications_count


# Select the data which have disagreeements (ratio disagreement / # identification > 0)
RatioMisIdSup0 <- subset(data, data$RatioMisId>0)

```

```{r Disagreement & taxon rank - Pie chart}

Taxon_rank<- plyr::count(RatioMisIdSup0, "taxon.rank")
# Counts the number of observations according to there taxonomic rank

Taxon_rank$freqlbls <- as.character(Taxon_rank$freq)
# Creates label for frequency plot

### bar plot taxon rank ~ total frequency###
ggplot(data=Taxon_rank, aes(x=taxon.rank, y=freq, fill = taxon.rank))+
  geom_bar(stat="identity",width=0.7, colour = "black")+
  xlab("Identification level")+
  ylab("Frequency of ID disagreeance")+
  ggtitle("More than 2/3 of the taxa disagreed upon are identified to species level")+
  scale_y_continuous()+
  scale_x_discrete(limits=c("species", "genus", "subgenus", "subfamily", "tribe"), labels = c("Species", "Genus", "Subgenus", "Subfamily", "Tribe"))+
  scale_fill_manual(name = "Taxonomic rank", labels = c("Genus", "Species", "Subfamily", "Subgenus", "Tribe"), values = c('#e66101','#fdb863','#f7f7f7','#b2abd2','#5e3c99'))+
  geom_text(aes(label=freqlbls), vjust=-0.5)+
  theme_bw()


Taxon_rank$pct <- round(Taxon_rank$freq/sum(Taxon_rank$freq)*100)
Taxon_rank$pctlbls <- as.character(Taxon_rank$pct)
Taxon_rank$pctlbls <- paste(Taxon_rank$pctlbls,"%",sep="") # add % to labels
# Creates label for % plot

### bar plot taxon rank ~ percent frequency###
ggplot(data=Taxon_rank, aes(x=taxon.rank, y=pct, fill = taxon.rank))+
  geom_bar(stat="identity",width=0.7, colour = "black")+
  xlab("Identification level")+
  ylab("Proportion of ID disagreeance (%)")+
  ggtitle("More than 2/3 of the taxa disagreed upon are identified to species level")+
  scale_y_continuous()+
  scale_x_discrete(limits=c("species", "genus", "subgenus", "subfamily", "tribe"), labels = c("Species", "Genus", "Subgenus", "Subfamily", "Tribe"))+
  scale_fill_manual(name = "Taxonomic rank", labels = c("Genus", "Species", "Subfamily", "Subgenus", "Tribe"), values = c('#e66101','#fdb863','#f7f7f7','#b2abd2','#5e3c99'))+
  geom_text(aes(label=pctlbls), vjust=-0.5)+
  theme_bw()

```